### PR TITLE
PR for the project Members_only

### PR DESCRIPTION
**Pull request by uchennaanya**
- This project is used to get our feet wet working on authorization and authentication using Rails' powerful DEVISE gem. In this project, a user can create a post, only a logged-in user can see the author of a post
- We create a user model and controller
- Create posts model and controller
- Install Devise

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Request Changes
Hello, @uchennaanya and @kunmi02 you have worked so hard on this project, and it's almost ready. Just very few issues to fix, that should not take you long.
- [ ] In the PostController ensure that it initializes an empty post `@post = Post.new` [Link](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png)

Feel free to reach me on slack [Oloo Moses] should you have any doubts or concerns

**Comment by kunmi02** [comment]
> # Status: Request Changes
> Hello, @uchennaanya and @kunmi02 you have worked so hard on this project, and it's almost ready. Just very few issues to fix, that should not take you long.
> 
> * [ ]  In the PostController ensure that it initializes an empty post `@post = Post.new` [Link](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png)
> 
> Feel free to reach me on slack [Oloo Moses] should you have any doubts or concerns

**Comment by kunmi02** [comment]
> # Status: Request Changes
> Hello, @uchennaanya and @kunmi02 you have worked so hard on this project, and it's almost ready. Just very few issues to fix, that should not take you long.
> 
> * [ ]  In the PostController ensure that it initializes an empty post `@post = Post.new` [Link](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png)
> 
> Feel free to reach me on slack [Oloo Moses] should you have any doubts or concerns

Hi @oloomoses ,

I think what that means is to create our #new method. Initializing the post with the @post = Post.new will break the app and moreso, using the devise, we have to build the post controller like `current_user.posts.build`.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

  - [ ]  Kindly work on the requirement as stated by the previous TSE
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
